"""Helper module to import Buildium SDK API classes."""

# Import SDK components (now a subpackage)
from mcp_server_buildium.buildium_sdk.api import (
    ApplicantsApi,
    AssociationOwnersApi,
    AssociationsApi,
    AssociationTenantsApi,
    AssociationUnitsApi,
    BankAccountsApi,
    BillsApi,
    BoardMembersApi,
    BudgetsApi,
    CommunicationsApi,
    ContactRequestsApi,
    FilesApi,
    GeneralLedgerApi,
    LeasesApi,
    LeaseTransactionsApi,
    ListingsApi,
    OwnershipAccountsApi,
    OwnershipAccountTransactionsApi,
    RentalOwnerRequestsApi,
    RentalOwnersApi,
    RentalPropertiesApi,
    RentalTenantsApi,
    RentalUnitsApi,
    ResidentRequestsApi,
    TasksApi,
    ToDoRequestsApi,
    VendorsApi,
    WorkOrdersApi,
)
from mcp_server_buildium.buildium_sdk.api_client import ApiClient
from mcp_server_buildium.buildium_sdk.configuration import Configuration

__all__ = [
    "ApiClient",
    "Configuration",
    "AssociationsApi",
    "LeasesApi",
    "LeaseTransactionsApi",
    "RentalPropertiesApi",
    "ApplicantsApi",
    "RentalTenantsApi",
    "AssociationTenantsApi",
    "RentalOwnersApi",
    "AssociationOwnersApi",
    "RentalUnitsApi",
    "AssociationUnitsApi",
    "VendorsApi",
    "TasksApi",
    "BillsApi",
    "FilesApi",
    "BankAccountsApi",
    "BoardMembersApi",
    "OwnershipAccountsApi",
    "OwnershipAccountTransactionsApi",
    "ListingsApi",
    "GeneralLedgerApi",
    "WorkOrdersApi",
    "CommunicationsApi",
    "BudgetsApi",
    "ContactRequestsApi",
    "ToDoRequestsApi",
    "ResidentRequestsApi",
    "RentalOwnerRequestsApi",
]
