#!/usr/bin/env python3
"""Generate a spec-coverage report mapping MCP tools to Buildium OpenAPI operations.

This is the concrete artifact that "validates the tools and functions against the
openapi." It loads ``openapi.json``, introspects the registered FastMCP tools and
their declared ``operationId`` mappings (``tools._common.TOOL_OPERATIONS``), and
writes ``docs/tool-coverage.md`` describing, for every tool:

* the OpenAPI ``operationId`` it targets,
* the HTTP method + path of that operation, and
* a status: ``OK`` (operation exists) or ``MISSING`` (no such operation).

It also lists high-value endpoints that no tool currently covers.

Usage::

    python scripts/generate_tool_coverage.py            # write docs/tool-coverage.md
    python scripts/generate_tool_coverage.py --check    # exit non-zero if stale/invalid
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
sys.path.insert(0, str(SRC))

OPENAPI_PATH = REPO_ROOT / "openapi.json"
REPORT_PATH = REPO_ROOT / "docs" / "tool-coverage.md"


def load_spec_operations(spec_path: Path) -> dict[str, dict[str, Any]]:
    """Return ``operationId -> {method, path, summary}`` from an OpenAPI document."""
    spec = json.loads(spec_path.read_text())
    operations: dict[str, dict[str, Any]] = {}
    for path, methods in spec.get("paths", {}).items():
        for method, op in methods.items():
            if not isinstance(op, dict):
                continue
            operation_id = op.get("operationId")
            if not operation_id:
                continue
            operations[operation_id] = {
                "method": method.upper(),
                "path": path,
                "summary": op.get("summary", ""),
            }
    return operations


def load_tool_mappings() -> tuple[list[str], dict[str, str]]:
    """Import the server and return (registered tool names, tool->operationId map)."""
    # Credentials are required to import the server; use placeholders for
    # introspection only (no network calls are made).
    os.environ.setdefault("BUILDIUM_CLIENT_ID", "coverage-introspection")
    os.environ.setdefault("BUILDIUM_CLIENT_SECRET", "coverage-introspection")

    from mcp_server_buildium import server
    from mcp_server_buildium.tools import _common

    tools = asyncio.run(server.mcp.list_tools())
    tool_names = sorted(t.name for t in tools)
    return tool_names, dict(_common.TOOL_OPERATIONS)


def build_report(
    tool_names: list[str],
    tool_operations: dict[str, str],
    spec_operations: dict[str, dict[str, Any]],
) -> str:
    """Render the Markdown coverage report."""
    lines: list[str] = []
    lines.append("# Tool Coverage Report")
    lines.append("")
    lines.append(
        "Generated by `scripts/generate_tool_coverage.py`. Do not edit by hand. "
        "This maps every MCP tool to the Buildium OpenAPI operation it exercises "
        "and validates that the operation exists in `openapi.json`."
    )
    lines.append("")

    covered_ops = set(tool_operations.values())
    ok = sum(1 for op in tool_operations.values() if op in spec_operations)
    missing = len(tool_operations) - ok

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Registered tools: **{len(tool_names)}**")
    lines.append(f"- Tools mapped to an OpenAPI operation: **{len(tool_operations)}**")
    lines.append(f"- Mappings valid (operation exists in spec): **{ok}**")
    lines.append(f"- Mappings invalid (operation missing): **{missing}**")
    lines.append(f"- Total operations in spec: **{len(spec_operations)}**")
    lines.append(f"- Spec operations covered by a tool: **{len(covered_ops & set(spec_operations))}**")
    lines.append("")

    lines.append("## Tool → Operation mapping")
    lines.append("")
    lines.append("| Tool | operationId | Method | Path | Status |")
    lines.append("| --- | --- | --- | --- | --- |")
    for tool in sorted(tool_operations):
        operation_id = tool_operations[tool]
        spec = spec_operations.get(operation_id)
        if spec:
            status = "OK"
            method = spec["method"]
            path = spec["path"]
        else:
            status = "MISSING"
            method = "-"
            path = "-"
        lines.append(f"| `{tool}` | `{operation_id}` | {method} | `{path}` | {status} |")
    lines.append("")

    # Tools with no operation mapping (e.g. health_check) are intentional and listed
    # separately so the report is complete.
    unmapped = sorted(set(tool_names) - set(tool_operations))
    if unmapped:
        lines.append("## Tools without a spec operation (server-local)")
        lines.append("")
        for tool in unmapped:
            lines.append(f"- `{tool}`")
        lines.append("")

    lines.append("## Uncovered spec operations")
    lines.append("")
    uncovered = sorted(set(spec_operations) - covered_ops)
    lines.append(
        f"{len(uncovered)} of {len(spec_operations)} OpenAPI operations are not yet "
        "exposed as tools. These are candidates for future expansion."
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any mapping is invalid or the report is stale.",
    )
    args = parser.parse_args()

    spec_operations = load_spec_operations(OPENAPI_PATH)
    tool_names, tool_operations = load_tool_mappings()

    invalid = {t: op for t, op in tool_operations.items() if op not in spec_operations}
    report = build_report(tool_names, tool_operations, spec_operations)

    if args.check:
        stale = not REPORT_PATH.exists() or REPORT_PATH.read_text() != report
        if invalid:
            print("Invalid tool→operation mappings (not in spec):", file=sys.stderr)
            for tool, op in sorted(invalid.items()):
                print(f"  {tool} -> {op}", file=sys.stderr)
        if stale:
            print(
                "docs/tool-coverage.md is stale. Run "
                "`python scripts/generate_tool_coverage.py`.",
                file=sys.stderr,
            )
        return 1 if (invalid or stale) else 0

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report)
    print(f"Wrote {REPORT_PATH.relative_to(REPO_ROOT)} ({len(tool_operations)} tools mapped).")
    if invalid:
        print(f"WARNING: {len(invalid)} invalid mapping(s) found.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
